#include "common.h"
#include "clock.h"
#include "disp.h"
#include "autogenerated/baloons.h"
#include "autogenerated/hearts.h"
#include <avr/io.h>
#include <util/delay.h>
#include <avr/sleep.h>
#include <avr/interrupt.h>
#include <stdint.h>

#define RIGHT_BUTTON (!(PIND & 0x20))
#define CENTER_BUTTON (!(PIND & 0x40))
#define LEFT_BUTTON (!(PIND & 0x80))

bool left_button_int = false;
bool center_button_int = false;
bool right_button_int = false;

void init(void) {
	/* start rtc */
	clk_start();
	/* set button pins for reading */
	DDRD &= 0x1F;
	/* init epaper display */
	disp_init();
	/* disable ADC */
	ADCSRA = 0;
	/* configure sleep mode */
	set_sleep_mode(SLEEP_MODE_PWR_DOWN);

	/* enable INT0 so RTC can wake up CPU from sleep */
	// set DDD2 as input
	DDRD &= ~(1 << DDD2);
	// set INT0 to occur on low level
	EICRA = 0;
	// enable INT0
	EIMSK |= (1 << INT0);
	// and enable interrupts
	sei();
}

void sleep(void) {
	sei();
	sleep_enable();
	sleep_bod_disable();
	sleep_cpu();
	sleep_disable();
	//clk_clear_alarm();
	cli();
}

uint8_t bcd_to_uint(uint8_t bcd) {
	return (bcd % 16) + ((bcd / 16) * 10);
}

uint8_t uint_to_bcd(uint8_t uint) {
	return (uint % 10) + ((uint / 10) * 16);
}

ISR(INT0_vect) {
	bool underscored[] = { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
	left_button_int = LEFT_BUTTON;
	center_button_int = CENTER_BUTTON;
	right_button_int = RIGHT_BUTTON;
	TIME time = {};
}

bool display_baloons(TIME *time) {
	if ((time->months == 0x08 && time->days == 0x31) ||
		(time->months == 0x09 && time->days == 0x21) ||
		(time->months == 0x10 && time->days == 0x11) ||
		(time->months == 0x11 && time->days == 0x05))
		return true;
	else
		return false;
}

bool display_hearts(TIME *time) {
	if ((time->months == 0x01 && time->days == 0x01) ||
		(time->months == 0x02 && time->days == 0x05) ||
		(time->months == 0x03 && time->days == 0x10) ||
		(time->months == 0x04 && time->days == 0x15) ||
		(time->months == 0x05 && time->days == 0x20) ||
		(time->months == 0x06 && time->days == 0x25) ||
		(time->months == 0x07 && time->days == 0x30))
		return true;
	else
		return false;
}

int main(void) {
	init();
	TIME time = {};
	uint8_t underscored_index = 0;
	uint8_t prev_min;
	bool refresh = true;
	bool underscored_tab[8][15] = {
		{false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
		{true, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
		{false, true, false, false, false, false, false, false, false, false, false, false, false, false, false},
		{false, false, false, true, false, false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, true, false, false, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, true, true, false, false, false, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, true, true, false, false, false, false, false},
		{false, false, false, false, false, false, false, false, false, false, false, true, true, true, true},
	};
	while (true) {
		/* get current time */
		prev_min = time.minutes;
		if (clk_get_time(&time) && time.minutes != prev_min) refresh = true;
		/* handle buttons */
		if (center_button_int) {
			center_button_int = 0;
			underscored_index += 1;
			underscored_index %= 8;
			if (underscored_index == 0) clk_start();
			else clk_stop();
			refresh = true;
		}
		else if (left_button_int || right_button_int)
		{
			refresh = true;
			time.seconds = 0x00;
			switch (underscored_index)
			{
			case 1:
				if (left_button_int && (time.hours & 0xF0) != 0x00) time.hours -= 0x10;
				else if (right_button_int && (time.hours & 0xF0) != 0x20) time.hours += 0x10;
				if (time.hours >= 0x24) time.hours = 0x23;
				break;
			case 2:
				if (left_button_int && (time.hours & 0x0F) != 0x00) time.hours -= 0x01;
				else if (right_button_int && (time.hours & 0x0F) != 0x09 && time.hours != 0x24) time.hours += 0x01;
				break;
			case 3:
				if (left_button_int && (time.minutes & 0xF0) != 0x00) time.minutes -= 0x10;
				else if (right_button_int && (time.minutes & 0xF0) != 0x50) time.minutes += 0x10;
				break;
			case 4:
				if (left_button_int && (time.minutes & 0x0F) != 0x00) time.minutes -= 0x01;
				else if (right_button_int && (time.minutes & 0x0F) != 0x09) time.minutes += 0x01;
				break;
			case 5:
				if (left_button_int && time.days != 0x01) time.days = uint_to_bcd(bcd_to_uint(time.days) - 1);
				else if(right_button_int && (time.days != 0x31)) time.days = uint_to_bcd(bcd_to_uint(time.days) + 1);
				break;
			case 6:
				if (left_button_int && time.months != 0x01) time.months = uint_to_bcd(bcd_to_uint(time.months) - 1);
				else if (right_button_int && (time.months != 0x12)) time.months = uint_to_bcd(bcd_to_uint(time.months) + 1);
				break;
			case 7:
				if (left_button_int && time.years != 0x00) time.years = uint_to_bcd(bcd_to_uint(time.years) - 1);
				else if (right_button_int && (time.years != 0x99)) time.years = uint_to_bcd(bcd_to_uint(time.years) + 1);
				break;
			default:
				break;
			}
			clk_set_time(&time);
		}
		/* write time to screen memory */
		if (refresh) {
			if (underscored_index == 0 && display_baloons(&time)) {
				disp_writeSmallTime(&time, baloons);
			}
			else if (underscored_index == 0 && display_hearts(&time)) {
				disp_writeSmallTime(&time, hearts);
			}
			else {
				disp_writeBigTime(&time, underscored_tab[underscored_index]);
				if (left_button_int || center_button_int || right_button_int) {
					/* repeat to clear buffers */
					/* inconsistency happens only if button was pressed to early */
					disp_writeBigTime(&time, underscored_tab[underscored_index]);
				}
			}
			/* and print it */
			disp_displayFrame();
			refresh = false;
			left_button_int = false;
			center_button_int = false;
			right_button_int = false;
		}
	}
	return 0;
}
