from PIL import Image
import sys
import os
from common import *


if len(sys.argv) != 2:
    print('Usage: bitmap.py <filename>')
    sys.exit(1)
filename = sys.argv[1]

img = Image.open('bitmaps/' + filename + '.png')
if not img:
    print('Error: can\'t open', filename)
    sys.exit(1)

img_list = compress_list(create_list_from_img(img))
cpp_array = create_cpp_array_from_list(img_list, filename)
code = create_cpp_code(cpp_array)
out = open('autogenerated/' + filename + '.h', 'wt')
out.write(code)
out.close()
